apiVersion: v1
data:
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::324813622390:user/github-ci
      username: github-ci
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::324813622390:role/AWS-EKS_NODE_ROLE
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
